#include <stdio.h>

#include <stdlib.h>

int main() 
{
   int _AAAAAAAAAAAAAAA, _DDDDDDDDDDDDDDD, _BBBBBBBBBBBBBBB, _XXXXXXXXXXXXXXX, _CCCCCCCCCCCCCCC, _ZZZZZZZZZZZZZZZ;
   printf("Enter _AAAAAAAAAAAAAAA:");
   scanf("%d", &_AAAAAAAAAAAAAAA);
   printf("Enter _BBBBBBBBBBBBBBB:");
   scanf("%d", &_BBBBBBBBBBBBBBB);
   for (int _DDDDDDDDDDDDDDD = _AAAAAAAAAAAAAAA; _DDDDDDDDDDDDDDD <= _BBBBBBBBBBBBBBB; _DDDDDDDDDDDDDDD++)
   printf("%d\n", _DDDDDDDDDDDDDDD * _DDDDDDDDDDDDDDD);
   for (int _DDDDDDDDDDDDDDD = _BBBBBBBBBBBBBBB; _DDDDDDDDDDDDDDD <= _AAAAAAAAAAAAAAA; _DDDDDDDDDDDDDDD++)
   printf("%d\n", _DDDDDDDDDDDDDDD * _DDDDDDDDDDDDDDD);
   _XXXXXXXXXXXXXXX = 0;
   _CCCCCCCCCCCCCCC = 0;
   while (_CCCCCCCCCCCCCCC < _AAAAAAAAAAAAAAA)
   {
   {
   _ZZZZZZZZZZZZZZZ = 0;
   while (_ZZZZZZZZZZZZZZZ < _BBBBBBBBBBBBBBB)
   {
   {
   _XXXXXXXXXXXXXXX = _XXXXXXXXXXXXXXX + 1;
   _ZZZZZZZZZZZZZZZ = _ZZZZZZZZZZZZZZZ + 1;
   }
   }
   _CCCCCCCCCCCCCCC = _CCCCCCCCCCCCCCC + 1;
   }
   }
   printf("%d\n", _XXXXXXXXXXXXXXX);
   _XXXXXXXXXXXXXXX = 0;
   _CCCCCCCCCCCCCCC = 1;
   do
   {
   _ZZZZZZZZZZZZZZZ = 1;
   do
   {
   _XXXXXXXXXXXXXXX = _XXXXXXXXXXXXXXX + 1;
   _ZZZZZZZZZZZZZZZ = _ZZZZZZZZZZZZZZZ + 1;
   }
   while (!(_ZZZZZZZZZZZZZZZ > _BBBBBBBBBBBBBBB));
   _CCCCCCCCCCCCCCC = _CCCCCCCCCCCCCCC + 1;
   }
   while (!(_CCCCCCCCCCCCCCC > _AAAAAAAAAAAAAAA));
   printf("%d\n", _XXXXXXXXXXXXXXX);
   system("pause");
    return 0;
}
