#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

int main() 
{
   int   _AAAAAAAAAAAAAAA, _DDDDDDDDDDDDDDD, _BBBBBBBBBBBBBBB, _XXXXXXXXXXXXXXX, _CCCCCCCCCCCCCCC, _YYYYYYYYYYYYYYY;
   printf("Enter _AAAAAAAAAAAAAAA:");
   scanf("%d", &_AAAAAAAAAAAAAAA);
   printf("Enter _BBBBBBBBBBBBBBB:");
   scanf("%d", &_BBBBBBBBBBBBBBB);
   for (_DDDDDDDDDDDDDDD = _AAAAAAAAAAAAAAA; _BBBBBBBBBBBBBBB >= _DDDDDDDDDDDDDDD; _DDDDDDDDDDDDDDD++)
   {
   printf("%d\n", _DDDDDDDDDDDDDDD * _DDDDDDDDDDDDDDD);
   }
   for (_DDDDDDDDDDDDDDD = _BBBBBBBBBBBBBBB; _AAAAAAAAAAAAAAA <= _DDDDDDDDDDDDDDD; _DDDDDDDDDDDDDDD--)
   {
   printf("%d\n", _DDDDDDDDDDDDDDD * _DDDDDDDDDDDDDDD);
   }
   _XXXXXXXXXXXXXXX = 0;
   _CCCCCCCCCCCCCCC = 0;
   while (_CCCCCCCCCCCCCCC < _AAAAAAAAAAAAAAA)
   {
   _YYYYYYYYYYYYYYY = 0;
   while (_YYYYYYYYYYYYYYY < _BBBBBBBBBBBBBBB)
   {
   _XXXXXXXXXXXXXXX = _XXXXXXXXXXXXXXX + 1;
   _YYYYYYYYYYYYYYY = _YYYYYYYYYYYYYYY + 1;
   }
   _CCCCCCCCCCCCCCC = _CCCCCCCCCCCCCCC + 1;
   }
   printf("%d\n", _XXXXXXXXXXXXXXX);
   _XXXXXXXXXXXXXXX = 0;
   _CCCCCCCCCCCCCCC = 1;
   do 
   { 
    _YYYYYYYYYYYYYYY = 1;
   do 
   { 
    _XXXXXXXXXXXXXXX = _XXXXXXXXXXXXXXX + 1;
   _YYYYYYYYYYYYYYY = _YYYYYYYYYYYYYYY + 1;
 
   }  while (!(_YYYYYYYYYYYYYYY > _BBBBBBBBBBBBBBB));
   _CCCCCCCCCCCCCCC = _CCCCCCCCCCCCCCC + 1;
 
   }  while (!(_CCCCCCCCCCCCCCC > _AAAAAAAAAAAAAAA));
   printf("%d\n", _XXXXXXXXXXXXXXX);
   system("pause");
    return 0;
}
